=== ikasanEIP/ikasan/common/src/test/resources/routerInJar_1_0.xsd
<?xml version="1.0"?>
<!-- 
# //
# //
# // $Id$
# // $URL$
# // 
# // ====================================================================
# // Ikasan Enterprise Integration Platform
# // Copyright (c) 2003-2008 Mizuho International plc. and individual contributors as indicated
# // by the @authors tag. See the copyright.txt in the distribution for a
# // full listing of individual contributors.
# //
# // This is free software; you can redistribute it and/or modify it
# // under the terms of the GNU Lesser General Public License as
# // published by the Free Software Foundation; either version 2.1 of
# // the License, or (at your option) any later version.
# //
# // This software is distributed in the hope that it will be useful,
# // but WITHOUT ANY WARRANTY; without even the implied warranty of
# // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# // Lesser General Public License for more details.
# //
# // You should have received a copy of the GNU Lesser General Public
# // License along with this software; if not, write to the 
# // Free Software Foundation Europe e.V. Talstrasse 110, 40217 Dusseldorf, Germany 
# // or see the FSF site: http://www.fsfeurope.org/.
# // ====================================================================
# //
# // Author:  Ikasan Development Team
# // 
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:annotation>
        <xsd:documentation>Ikasan Router definition.</xsd:documentation>
    </xsd:annotation>

    <!-- root -->
    <xsd:element name="Router" type="RouterType"/>

    <!-- router configurations -->
    <xsd:complexType name="RouterType">
        <xsd:sequence>
            <xsd:element name="Component" type="ComponentType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="version" type="xsd:string" use="required" fixed="1.0"/>
    </xsd:complexType>

    <xsd:complexType name="ComponentType">
        <xsd:choice>
            <xsd:element name="Xpath" type="XpathType"/>
        </xsd:choice>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="XpathType">
        <xsd:sequence>
            <xsd:element name="Match" type="MatchType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="Default" type="DefaultType" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="expression" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="MatchType">
        <xsd:sequence>
            <xsd:element name="Target" type="TargetType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="result" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="DefaultType">
        <xsd:sequence>
            <xsd:element name="Target" type="TargetType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="TargetType">
        <xsd:simpleContent>
          <xsd:extension base="xsd:string">
            <xsd:attribute name="ignoreFail" type="xsd:boolean" default="false" use="optional"/>
          </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

</xsd:schema>

=== ikasanEIP/ikasan/common/src/test/resources/routerInJar.xml
<?xml version="1.0"?>
<!-- 
# //
# //
# // $Id: routerInJar.xml 16606 2009-04-09 08:07:33Z mitcje $
# // $URL: svn+ssh://svc-vcsp/architecture/ikasan/trunk/common/src/test/resources/routerInJar.xml $
# // 
# // ====================================================================
# // Ikasan Enterprise Integration Platform
# // Copyright (c) 2003-2008 Mizuho International plc. and individual contributors as indicated
# // by the @authors tag. See the copyright.txt in the distribution for a
# // full listing of individual contributors.
# //
# // This is free software; you can redistribute it and/or modify it
# // under the terms of the GNU Lesser General Public License as
# // published by the Free Software Foundation; either version 2.1 of
# // the License, or (at your option) any later version.
# //
# // This software is distributed in the hope that it will be useful,
# // but WITHOUT ANY WARRANTY; without even the implied warranty of
# // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# // Lesser General Public License for more details.
# //
# // You should have received a copy of the GNU Lesser General Public
# // License along with this software; if not, write to the 
# // Free Software Foundation Europe e.V. Talstrasse 110, 40217 Dusseldorf, Germany 
# // or see the FSF site: http://www.fsfeurope.org/.
# // ====================================================================
# //
# // Author:  Ikasan Development Team
# // 
-->
<Router version="1.0" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="routerInJar_1_0.xsd">

  <Component name="trax2-trax2Gateway-submitHandler">
      <Xpath expression="name(/*)">

        <!-- normal CMF to TRAX msgs -->
        <Match result="cmf:transactionRequest">
           <Target>@SUBPROJECT_NAME@-@COMPONENT_GROUP_NAME@-cmfToTrax2Transformer</Target>
        </Match>
        <Match result="cmf:statementRequest">
           <Target>@SUBPROJECT_NAME@-@COMPONENT_GROUP_NAME@-cmfToTrax2Transformer</Target>
        </Match>
        <Match result="cmf:searchRequest">
           <Target>@SUBPROJECT_NAME@-@COMPONENT_GROUP_NAME@-cmfToTrax2Transformer</Target>
        </Match>

        <!-- normal TRAX to CMF msgs -->
        <Match result="TransactionResponse">
           <Target>@SUBPROJECT_NAME@-@COMPONENT_GROUP_NAME@-trax2ToCmfTransformer</Target>
        </Match>
        <Match result="StatementResponse">
           <Target>@SUBPROJECT_NAME@-@COMPONENT_GROUP_NAME@-trax2ToCmfTransformer</Target>
        </Match>
        <Match result="SearchResponse">
           <Target>@SUBPROJECT_NAME@-@COMPONENT_GROUP_NAME@-trax2ToCmfTransformer</Target>
        </Match>
        <Match result="GeneralResponse">
           <Target ignoreFail="false">@SUBPROJECT_NAME@-@COMPONENT_GROUP_NAME@-trax2ToCmfTransformer</Target>
        </Match>

        <!-- what to do if no match -->
        <Default>
           <Target ignoreFail="false">@SUBPROJECT_NAME@-@COMPONENT_GROUP_NAME@-exceptionHandler</Target>
        </Default>
        
      </Xpath>
    </Component>
     
</Router>
